### ISSUE TITLE
update gmod_gene_families.pl to help more with the non-tree-based ways of proceeding

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/gcv#106]
probably just adding an option that could be used to collect all featureprops with the appropriate type_id and do the needful to add them to gene_family_assignments would be less hacky than my current post-processing insert SQL approach (though perhaps the insert SQL I use would be a better or at least easier approach to use in the script than the current plodding through of the hash?)

**Comment by alancleary** [comment]
Stale. Closing.
