### ISSUE TITLE
make the track detail component use "dynamic discovery" (aka linkout service)

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/gcv#129]
currently the ability to take the set of genes in a track and send to a Mine is basically hardcoded into the legumeinfo-settings and legfed-settings branches. The latter's implementation is especially ridiculous in that the client has to deal with a lot of details pertaining to the source of the tracks and the appropriate Mine to send the gene list to. It would be better to just make use of the linkout service (which may or may not already have a set-oriented version; if it doesn't it should)

**Comment by alancleary** [comment]
@adf-ncgr Do you already have a service running that I can test against? If not, do you have a specification? If not, I could just replicate the code from the gene link-out functionality with minor changes for passing a list of genes, rather than a single gene.

**Comment by alancleary** [comment]
Technically closed. Can't remember when but @adf-ncgr said so.
