### ISSUE TITLE
'Singletons' in Micro-Synteny legend lists singleton families but not genes

### ISSUE THREAD

**Issue by svengato** [legumeinfo/gcv#257]
When you mouse over an individual singleton gene in the Micro-Synteny panel, the message contains that gene's name (the list of genes contains one item, the selected gene). But when you mouse over the Singletons "gene family" in the Micro-Synteny legend, the list of genes is empty. Shouldn't it list all singleton genes in the visible region?
(It does list the gene families, as "singleton,phytozome_10_2.xxxxxxxx,phytozome_10_2.yyyyyyyy,...")

**Comment by svengato** [comment]
Possibly related:
When you mouse over a gene family, it used to send a message containing the gene family and a list of related genes. Now it only includes the gene family - is this correct? In ZZBrowse, I have a workaround where I get the related genes from the annotations instead.

(My version uses legfed_v1_0 gene families instead of phytozome, if that matters.)

**Comment by alancleary** [comment]
@svengato Is this still an issue for you? I can't replicate the behavior you described with the code in the main branch, i.e. when I mouse over the "singletons" (or any other) family all the genes are highlighted properly and the message sent over the broadcast channel contains a "target" entry that lists all singleton genes. Similarly, clicking on the "singletons" family correctly lists all singleton genes in the view.

**Comment by svengato** [comment]
It looks like it is working, but that may be due to the workaround mentioned above. If I remember correctly, the 'targets' object used to have both 'family' and 'genes' data, but now it just has 'family' and I get the genes elsewhere. I may also be using an older version of the GCV.

![Screen Shot 2022-04-25 at 16 21 21](https://user-images.githubusercontent.com/8918336/165185065-5be87d5e-6e3e-48e6-9759-96cc1d1045fb.png)

I will have to look at it in more detail.

**Comment by alancleary** [comment]
Ah, that's right. Those are all the orphan families, not the gene names. I'll dig into this. Thanks!

**Comment by svengato** [comment]
-Singleton- families?

**Comment by alancleary** [comment]
> -Singleton- families?

In your example, the singleton "family" has broadcast a comma separated list containing every family that occurs once in the view. Note that this list is concatenated into a single string, per the [GCV broadcast channel API](https://github.com/legumeinfo/gcv/wiki/Inter-Application-Communication#minimum-viable-messages). Why is the value an array in your example? Did this come directly from GCV?

**Comment by svengato** [comment]
It comes directly from the GCV, but Shiny.onInputChange() internally converts it to an R list (presumably using fromJSON() or equivalent).

**Comment by alancleary** [comment]
OK, thanks for clarifying.

**Comment by alancleary** [comment]
Done in commit d8691a54be73ff39f95c728d4c6d68125cdb3fa3, which will be included in release 2.3.0. Closing.
