### ISSUE TITLE
what to do about our macrosynteny "steering column"

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/gcv#275]
the big vertical bar in the macrosynteny view no longer seems to be motile, ie it can't be dragged to reposition the microview. I can imagine that this is more complicated in GCV2.0 world given that there's not a one-to-one relationship between micro/macro. Or maybe the real complication is that the micro doesn't have a master query track like it used to? In the latter case, we might think about facilitating the GCV1->2 transition of our user base by re-enabling motility in the case where a microview is representing a single-query case. In any case, the big vert bar is still a useful marker of position in macroland even whilst remaining sessile.

**Comment by alancleary** [comment]
Previously when the vertical bar was moved the new physical location on the reference chromosome would be resolved by the client into the nearest gene which would then be used for a new search query. In the new data model the physical locations of the reference chromosome's gene are no longer on hand. I haven't really taken the time to tussle with this issue but I agree that it should be reimplemented. A few possible options are:

1. Add a nearest gene service that resolves a coordinate on a chromosome into a gene
2. Wait until the new search functionality is implemented and perform a chromosome coordinate/interval search to resolve the gene
3. Assume the genes are uniformly distributed on the reference chromosome (which they're not) and resolve the coordinate into a gene client-side based on this assumption

I was hoping an elegant solution to this would come to me while working on other issue, but alas, I am empty handed.

**Comment by alancleary** [comment]
This appesrs to be fixed, although I don't know when...
