### ISSUE TITLE
look at minimizing extra download bloat from screenshots on instructions page

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/gcv#301]
per @nathanweeks suggestion. I'm not going to dive in as it occurred to me that the plan we recently discussed for having enlarged lightboxed images may contradict some of what he was thinking should be done. That said, since many of the images are essentially cropped versions
of subcomponents of the main one, it seems like we might be able to effect some reduction by using a single image and cropping it differently (e.g. via CSS clip) in the different contexts in which it appears. This may be a dumb idea for some reason, but offhand it seems to make sense.

**Comment by alancleary** [comment]
Since we want site admins to be able to upload their own images I don't think cropping one image in browser is the right solution.

I'll just implement the lightbox you mentioned and add the option to upload a thumbnail. The thumbnail will be used in the main instructions page but clicking on it will open a lightbox and load the full resolution image.

**Comment by adf-ncgr** [comment]
sounds good, although TBH I am not sure we will ever meet the site admin dedicated enough to go to the trouble of updating all those images and captions!

**Comment by alancleary** [comment]
This is somewhat out of scope in that it's only related to download bloat in general but I add instructions on how to optionally compress the client build using Brotli to the readme in commit a1ea59853b6b3c180b564a10a41ed84abf505a59.

**Comment by alancleary** [comment]
Commit 00595cdc0257b43817f386740ae4e85d3a6b7de5 added GIFs to be used in place of the original PNG screenshots. It also adds a lazy load directive that doesn't load the images until they're in view.

Apparently implementing a lightbox that lets images be as large as possible within a bounded area AND has a caption is difficult. So I'll defer that feature to after the v2 release. In the meantime, I added the caption for the title screenshot to the image using the text attribute so users can still see the explanation of that particular view.

**Comment by alancleary** [comment]
@adf-ncgr's last comment about web admins is a good point. I think part of the technical solution here should be to have GCV scan its images and generate smaller resolution versions at startup (if they don't already exist). Pairing this with the [responsive image tags](https://developer.mozilla.org/en-US/docs/Learn/HTML/Multimedia_and_embedding/Responsive_images) and the lazy loading that has already been implemented should make things real quick!

I'll also note that commit bdae4ce4764f545c6416f63b3663fbea7e83e1b2 enabled [AOT compiling](https://angular.io/guide/aot-compiler) of GCV which should greatly reduce the size of the JS files that need to be loaded before GCC can run.

**Comment by alancleary** [comment]
I finally implemented the aforementioned lightbox in commit 1728ea3c9f9ee9ac88ece9eb3024555e98dfd42e. However, the lightbox and the images within the instructions page are still simply whatever is provided in the config file. Next I will update these image tags to be responsive, also previously mentioned.

**Comment by alancleary** [comment]
Commit 7ae3af8690967533036d2e065076a419f094b58d added support for responsive images to the config file.

Commit 0c3863d2daba29f515bdb66f56b3fa88ee03c9ac updated the screenshot component to use the LazyLoad JavaScript library which will lazy load images on the instructions page when they come into view and supports responsive image sizing.

Commit a7d29c7db65d5788bdc637221755908a5e83bf1b updated the script that generates scaled copies of screenshots for lazy loading to generate image sizes that match the ideal sizes in the instructions page.

Commit 553297f775b6b3be5b5e6aa0fc32576ebe301017 added scaled copies of the screenshots so the appropriate sizes will be responsively loaded by the instructions page.

**Comment by alancleary** [comment]
Updated the config file Wiki page to document how to use screenshots with responsive image sizes.

Closing.
