### ISSUE TITLE
allow default parameters to be set in config file

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/gcv#308]
so people don't have to sully themselves with doing it via tweaks to the code file where this is now maintained; maybe a classic case of 6:half-dozen, but if it's easy to enable I guess it seems more consistent.

**Comment by alancleary** [comment]
Done in commit 3844bf9819434d5c6e4c9a5fe50fbb9aa4df87aa. However, the config documentation in the Wiki still needs to be updated.

**Comment by alancleary** [comment]
Default parameters have been added to the config file schema in the Wiki. Closing.
