### ISSUE TITLE
gRPC, HTTP REST, OpenAPI, and multiplexing

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/gcv#324]
I found an interesting project called [grpc-gateway](https://grpc-ecosystem.github.io/grpc-gateway/). It provides a protoc plugin that allows you to generate an [OpenAPI REST API](https://swagger.io/specification/) from your gRPC protobuffer. It can also generate a multiplexing server that lets you serve the REST API and gRPC API on the same port. In other words, it's letting you serve your API via two different protocols at the same endpoint, which could be very handy for services that serve requests directly from users via HTTP and serve inter-service requests via gRPC.

Unfortunately, the plugin [only generates a Go implementation of the mux server](https://grpc-ecosystem.github.io/grpc-gateway/docs/usage.html). However, the OpenAPI REST API it generates could be used to generate client/server code via a tool like [OpenAPI Generator](https://openapi-generator.tech/). Even without the mux server, this could help us rapidly develop and document services, and it would help developers that want to use our service APIs rapidly generate code to consume them. The mux server would just be the cherry on top.

I spent some time playing with this. Automating the code generation requires a bit of work up front, but then developing a service is simply a matter of defining you gRPC API, generating your OpenAPI and gRPC/HTTP stubs, and then writing the generic request handler.

I think this is a bit overkill for the GCV search services, but as our use of microservices grows beyond GCV and services start to not necessarily belong to a specific client, this may be worth considering as a project-wide protocol. But that's just my opinion. I've taken the time to write this up so other people who may have opinions can chime in: @adf-ncgr, @joelb123, @ctcncgr.

**Comment by adf-ncgr** [comment]
agreed that it seems overkill for the GCV search services, but also that it seems interesting and may have applications if our commitment to microservices as a way of life develops further momentum. I am not clear on gRPC's place in our systems but it sounds like the idea is to have a more efficient distributed communication protocol when you are within a trusted network context- let me know if that's off-base. It would be good to come up with a compelling use case to justify looking into it further. Not sure how helpful this comment is, but your issue seemed lonely...

**Comment by alancleary** [comment]
> I am not clear on gRPC's place in our systems but it sounds like the idea is to have a more efficient distributed communication protocol when you are within a trusted network context- let me know if that's off-base.

That's more or less the idea. Inter-service communication should certainly be done with gRPC because it's much more efficient than REST. Of course there's nothing precluding client code from making requests via gRPC, but I think supporting REST is more community friendly.

> It would be good to come up with a compelling use case to justify looking into it further.

Federation and grants comes to mind.

**Comment by adf-ncgr** [comment]
OK, I was for some reason thinking it used a non-HTTP protocol but I guess that's not the case. I still bear scars of the SOAP vs REST for web-services wars, which once brainwashed me into believing anything that used HTTP in a non-RESTful way was a perversion of Roy Fielding's intent. Do you see any advantage to switching the GCV client-services communication to gRPC? (while leaving the RESTful versions of the service interface in place for the other consumers in the community, like ZBrowse). You had me at federation...

**Comment by joelb123** [comment]
While I don't have any doubt that the 2020 way of building things is around gRPC, I find the grpc-gateway a bit low-level and beside the point of how to deliver the data.  I subscribe to the view that the data are the API, by which I mean that a key part of architecting is figuring out  views of the data for which subsetting (as opposed to joining) is >90% of what is required.

Take a look at this talk: https://www.slideshare.net/mobile/wesm/apache-arrow-a-new-gold-standard-for-data-transport and
this code snippet: https://github.com/wesm/vldb-2019-apache-arrow-workshop/blob/90d1d79de6388d2bdbf1be134bd71acda006e5cf/Demo2-Flight.ipynb.

I'd like to talk about this on Monday.

**Comment by alancleary** [comment]
> Do you see any advantage to switching the GCV client-services communication to gRPC?

Speed is probably the biggest advantage. gRPC compresses messages as binary before transmitting so they should be smaller and, thus, transmit faster. The binary (de)serialization is also supposed to be much faster than JSON (de)serialization. This will probably make the most noticeable difference with the macro-synteny service, where entire chromosomes as ordered lists of functional annotations are being passed around. We should definitely do some benchmarking before seriously considering switching.

> I find the grpc-gateway a bit low-level and beside the point of how to deliver the data. ... Take a look at this talk: https://www.slideshare.net/mobile/wesm/apache-arrow-a-new-gold-standard-for-data-transport ...

Thanks for the response, @joelb123. I think Arrow is intended for much larger amounts of data than would ever be served via a REST API. I threw gRPC in the mix to improve inter-service communication performance and provide the same benefits to clients that want it, but I don't intend to use it to serve any data that couldn't reasonably be served with REST. Do you have thoughts on using OpenAPI specifications (possibly generated from gRPC) to generate client/server stubs? If I remember correctly, you've worked with Swagger in the past.

**Comment by joelb123** [comment]
I agree that you wouldn't serve up Arrow objects via a REST API, but I think the objects we should be dealing with are best thought of as larger views of data than we have been using in the past.   I've been making Parquet files of proteome and homology views and I expect to be adding a synteny view soon.  Deserialization to Pandas is something like 30X faster than with TSV, something like 100X faster when left as Arrow object, and metadata doesn't get lost the way it does with TSV (not to imply that TSV is the best way to go for anything other than viewing with a spreadsheet).  I believe it's worth considering whether these views would be a good basis for many services.

**Comment by alancleary** [comment]
> I agree that you wouldn't serve up Arrow objects via a REST API, but I think the objects we should be dealing with are best thought of as larger views of data than we have been using in the past. ...  I believe it's worth considering whether these views would be a good basis for many services.

I can certainly see building services on Arrow. However, I imagine such services would be doing analytics on behalf of the users and the users would consume the results via a more traditional protocol, such as REST. Of course we could make the underlying Arrow API accessible for users that want to consume it. My intention with this thread, though, is to consider generating code from REST/gRPC API specifications, or vice versa, because whether or not we use frameworks like Arrow, I think REST (and possibly gRPC) very much have a place in a community oriented microservices architecture.

**Comment by joelb123** [comment]
After thinking about it more, I believe I was wrong in agreeing with you that one wouldn't serve Arrow objects via a REST API.  I also think the question of REST vs. not is not the one I would focus on for now.

The question that comes up to the architect of a service is what organization makes most sense for that service.  The example you give of the service is macrosyntenic views.  To me, that says mostly-read-only tables and nowadays tables are best served by columnar organization because of the extreme advantages in deserialization and on-the-fly compression via HTTP/2.  This is exactly the use case of Arrow for in-memory and in-flight structures and Parquet for on-disk serialization.  While they are just "glue logic" before or on top of gRPC, they're huge amounts of glue logic that is worth considering using from the start whenever one needs to serve up tables.  I believe there is considerable overlap between problems we care about and the things the data lake people work on.  Though our space is terabytes in data sizes, not petabytes, it's quickly headed toward being too big to fit into memory on a single server, yet enabling single-server use cases is important.

There are several projects that address this space (on either frontend or backend) at a higher level than gRPC, some of which are open-source (or at least free for public data) that as architects we should look at.  Whether they are microservices is not particular important to me at the moment.  Most are GPU-enabled or WebAssembly-based, which seems where the future is headed.

- [Dremio](https://www.dremio.com/)
- [Falcon](https://github.com/uwdata/falcon)
- [OmniSciDB](https://github.com/omnisci/omniscidb)
- [FastData.IO](https://fastdata.io/why-fastdata/)
- [Perspective](https://github.com/finos/perspective)
- [QuiltData](https://quiltdata.com)
- [SciDB](https://paradigm4.com)
- [TileDB](https://github.com/TileDB-Inc/TileDB)

Several of these are actively used in genomics projects, mainly in pharma so far as I can tell.

**Comment by alancleary** [comment]
> After thinking about it more, I believe I was wrong in agreeing with you that one wouldn't serve Arrow objects via a REST API.

I should've been more explicit in my earlier comment about Arrow and REST. When I said "I think Arrow is intended for much larger amounts of data than would ever be served via a REST API" I was implying that the REST APIs in question would be dealing with data formats typically associated with REST APIs, e.g. JSON. So if Arrow were involved, it would be because there's too much data to be reasonably handled by these typical encodings.

> I also think the question of REST vs. not is not the one I would focus on for now.

I suppose I didn't explicitly ask a question in my original post, so let me ask it now: **REST is a protocol we currently use in many of our services. However, we don't have a formal method for documenting our REST APIs or guaranteeing that our service endpoints actually conform to the APIs. Additionally, we may want to serve the same APIs over different protocols, such as gRPC. Making sure APIs are consistent across protocols, that they are sufficiently documented for developers, and that they conform to the documentation are important problems we will have to address as we move into microservices because we will have many more services to manage and we, as developers, will need to consume APIs that we didn't necessarily develop. Using grpc-gateway and OpenAPI generator seems like good way to make APIs consistent across protocols (REST and gRPC) while providing documentation and guaranteeing that the service endpoints conform to the API. What do people think of this stack? Does anyone have experience formally defining APIs (across multiple protocols) and generating code to serve/consume them?**

> The question that comes up to the architect of a service is what organization makes most sense for that service.

This is the philosophy of microservices. The only constraint is that the protocol of the API consumed by clients is consistent across services. Whether protocol consistency is implemented across services or achieved via a translation/gateway server is an implementation detail.

> The example you give of the service is macrosyntenic views. To me, that says mostly-read-only tables and nowadays tables are best served by columnar organization because of the extreme advantages in deserialization and on-the-fly compression via HTTP/2.

I think "mostly-read-only tables", or WORM (write once read many), is an accurate description of the LIS database in general. WORM, however, doesn't necessarily imply OLAP (online analytical processing) access patterns, which are commonly facilitated via columnar database systems. For example, when the GCV macro-synteny service was suffering from poor run-time performance, I prototyped a handful of alternative implementations, including stacks based on Parquet, Spark, and Pandas. In this case, the run-time performance of these technologies was uninspiring and certainly didn't justify the overhead/complexity of their implementations. Ultimately, simply switching to an in-memory key-value database system was by far the most performant solution.

**Comment by alancleary** [comment]
Closing. Though I will note that this discussion may be worth keeping in mind as LIS moves forward with its restructuring. @cann0010 may want to give it a read if we're thinking microservices has a place in the future stack.
