### ISSUE TITLE
Automate docker image versioning, generation, and publication to Docker Hub

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/gcv#362]
This will make deployment easier, especially for site admins outside of our group who don't necessarily want to be cloning multiple repositories to get an instance of GCV up and running.

For the GCV client, the automation should be fairly straightforward since GitHub provides methods for pushing an image to Docker every time a release is tagged. The microservices, however, may require something more sophisticated since they're located in a mono repo but each microservice is individually versioned.

**Comment by adf-ncgr** [comment]
I'm still not completely sold on the mono repo idea, for reasons similar to what you describe here. Also thinking about how it would seem to complicate things with respect to outside groups who might want to fork code that represented somewhat logical groupings rather than the kitchen sink of leguminosity. And what if we decide to adopt microservices implemented elsewhere? Will we do unto ourselves as we would do unto others? Not completely opposed to it (and of course, you get more votes than I do since you are the benevolent tyrant), just think it is probably worth some further discussion before we commit to anything.

**Comment by alancleary** [comment]
@adf-ncgr Lucky for us, git has the "sparse-checkout" command, which allows developers to checkout a specific subset of a repository. This will be nice for LIS devs because it will allow each dev to only checkout the parts of the microservices repo that are relevant to their app. The sparse-checkout command can also be used for making a "partial clone" of a repository, where only a specific subset of the repository is actually cloned. This will accommodate the "outside groups" scenario you described.

Here's a GitHub post that discusses using the sparse-checkout command on a monorepo: https://github.blog/2020-01-17-bring-your-monorepo-down-to-size-with-sparse-checkout/

More practically, I think using a monorepo to house all the LIS microservices will keep our GitHub organization from descending into madness and anarchy. GCV alone has 11 microservices. If each service had its own repo it would already be bloating our GitHub repository list. Now imagine if every app's backend was replaced with microservices and each microservice was given its own repo. Madness! Of course there's the middle ground where each app has a repo containing all its services, but then it becomes awkward when two apps share a service. Who owns the service? How are they deployed? Does a developer that doesn't own a service have to clone its app's entire service repo to make changes to that one service or should they use the sparse-checkout command? And if they're using the sparse-checkout command then are we really that far removed from a monorepo?

**Comment by adf-ncgr** [comment]
Thanks, I will check out (sparsely) that blog post which certainly appears to be apposite to this discussion given that they use the example: example-microservices-in-a-monorepo 

just don't tell @svengato that you are opposed to anarchy (or Madness)...

**Comment by alancleary** [comment]
It turns out this is quite easy to achieve with Docker Hub. Basically you create a Docker Hub repository for each microservice and link each repository to the gcv-microservices GitHub repository. You then add an automated build rule to each repository that uses its microservice's subdirectory in the gcv-microservices repo as the build context and only builds when a tag specific to that microservice is committed. For example, if the tag source /^genes@v([0-9.]+)$/ is used then only tags like genes@v1.2.3 will trigger a build.

I'm going to use this strategy to automate microservice builds, version tagging, and publishing to Docker Hub. I know you're not sold on the monorepo @adf-ncgr but the build rules on Docker Hub can always be revised if we decide to reorganize things on GitHub.

**Comment by alancleary** [comment]
Building and pushing microservice images were automated with a GitHub workfile in commits 4ae6bcdb12cf4146b2a42acfa2ca5714a6a3bb6d and a8eba759a56fb6ec408603b0d5e0bb199413e813.

**Comment by alancleary** [comment]
Building and pushing GCV images was automated with a GItHub workflow in commit 56814566c558e1772a073e8eb6311a3a686ef4d0.
