### ISSUE TITLE
Docker Compose: npm ERR! could not determine executable to run

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/gcv#399]
When running GCV with docker compose, the service crashes immediately with the error:
```shell
npm ERR! could not determine executable to run
```
However, running the container directly with `docker run` doesn't cause the error.

@nathanweeks any idea what might be happening here?

**Comment by nathanweeks** [comment]
Probably a duplicate of https://github.com/legumeinfo/gcv/issues/397

**Comment by alancleary** [comment]
Thanks! For some reason I thought that one had already been closed. I'll close this one and follow up there.
