### ISSUE TITLE
loader explicit saves are running afoul of redisearch background saves?

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/gcv#414]
this (see below for error log) is happening (occasionally) in the context of the entrypoint loading script that @nathanweeks asked me to help flesh out with respect to the set of data we currently have loaded in the legumeinfo instance. It seems to be an issue of timing, as it sometimes seems to happen and other times not. But when it does happen the service exits with a non-zero status and dependent services fail to start. I haven't seen this issue prior to trying to use the loader in this way (possibly the timing become more of an issue when the datafiles are being downloaded from the remote datastore?)

test-redisearch-1                     | 1:M 05 Mar 2022 23:18:04.163 * Background saving started by pid 120
test-redis_loader-1                   | Traceback (most recent call last):
test-redis_loader-1                   |   File "/usr/local/lib/python3.9/runpy.py", line 197, in _run_module_as_main
test-redis_loader-1                   |     return _run_code(code, main_globals, None,
test-redis_loader-1                   |   File "/usr/local/lib/python3.9/runpy.py", line 87, in _run_code
test-redis_loader-1                   |     exec(code, run_globals)
test-redis_loader-1                   |   File "/usr/local/lib/python3.9/site-packages/redis_loader/__main__.py", line 326, in <module>
test-redis_loader-1                   |     main()
test-redis_loader-1                   |   File "/usr/local/lib/python3.9/site-packages/redis_loader/__main__.py", line 322, in main
test-redis_loader-1                   |     args.command(loader, args)
test-redis_loader-1                   |   File "/usr/local/lib/python3.9/site-packages/redis_loader/loaders/redisearch.py", line 59, in __exit__
test-redis_loader-1                   |     self.close()
test-redis_loader-1                   |   File "/usr/local/lib/python3.9/site-packages/redis_loader/loaders/redisearch.py", line 202, in close
test-redis_loader-1                   |     self.save()
test-redis_loader-1                   |   File "/usr/local/lib/python3.9/site-packages/redis_loader/loaders/redisearch.py", line 196, in save
test-redis_loader-1                   |     self.redis_connection.save()
test-redis_loader-1                   |   File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 1385, in save
test-redis_loader-1                   |     return self.execute_command('SAVE')
test-redis_loader-1                   |   File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 901, in execute_command
test-redis_loader-1                   |     return self.parse_response(conn, command_name, **options)
test-redis_loader-1                   |   File "/usr/local/lib/python3.9/site-packages/redis/client.py", line 915, in parse_response
test-redis_loader-1                   |     response = connection.read_response()
test-redis_loader-1                   |   File "/usr/local/lib/python3.9/site-packages/redis/connection.py", line 756, in read_response
test-redis_loader-1                   |     raise response
test-redis_loader-1                   | redis.exceptions.ResponseError: Background save already in progress
test-redisearch-1                     | 120:C 05 Mar 2022 23:18:12.971 * DB saved on disk
test-redisearch-1                     | 120:C 05 Mar 2022 23:18:13.067 * RDB: 7 MB of memory used by copy-on-write
test-redisearch-1                     | 1:M 05 Mar 2022 23:18:13.833 * Background saving terminated with success

**Comment by nathanweeks** [comment]
It looks like this should be work-aroundable by disabling the background save (which shouldn't be needed anyway, as the [redis_loader saves after every load](https://github.com/legumeinfo/microservices/blob/c35ad034ec9ce0c1d17619bace91f001ac2e3047/redis_loader/redis_loader/loaders/redisearch.py#L202)). For the production gcv.legumeinfo.org branch, I think this could be implemented thus (adding the `redis-server` `--save ''` option/option-argument to the existing `redis-server  --loadmodule /usr/lib/redis/modules/redisearch.so` that's baked into the redisearch Dockerfile CMD):
```
--- a/microservices/compose.prod.yml
+++ b/microservices/compose.prod.yml
@@ -43,6 +43,10 @@ services:
     # deployment github action workflow causes it to be recreated
     volumes:
       - /data
+    command: >
+      redis-server
+      --loadmodule /usr/lib/redis/modules/redisearch.so
+      --save ''
```

If this is the way to do it, it seems it would make sense in both development (microservices/compose.yml) as well as production (microservices/compose.prod.yml). And maybe a solution should go in the `main` branch first, and be merged/cherry-picked into gcv.legumeinfo.org (or is vice-versa OK)?

**Comment by adf-ncgr** [comment]
Thanks @nathanweeks ; this seems to have some conceptual overlap with a discussion that @alancleary and I had started sometime last year over [here](https://github.com/legumeinfo/microservices/issues/33#issuecomment-916314356)
to my way of thinking not having the server auto-saving seems to make most sense for the way we're using it, sounds like you are more or less thinking this too?

**Comment by nathanweeks** [comment]
> Thanks @nathanweeks ; this seems to have some conceptual overlap with a discussion that @alancleary and I had started sometime last year over [here](https://github.com/legumeinfo/microservices/issues/33#issuecomment-916314356) to my way of thinking not having the server auto-saving seems to make most sense for the way we're using it, sounds like you are more or less thinking this too?

@adf-ncgr definitely looks like related. AFAIK (1) is the current redis_loader behavior; https://github.com/legumeinfo/gcv/issues/414#issuecomment-1062474747 would implement (2) (in the manner @alancleary mentioned in  https://github.com/legumeinfo/microservices/issues/33#issuecomment-916328568), and you effectively implemented (3 (a)) in https://github.com/legumeinfo/gcv/commit/8bdf50532819d22cca9c3b6a5ab6a28fc3cc71a2 .  If the loader shell script failed part way through, one could `docker compose restart redisearch` to reload redis from the last explicit snapshot, before manually tweaking the erroneous load command & continuing (after commenting-out previous load commands that worked---data loading is a messy business).

**Comment by nathanweeks** [comment]
> I agree that it appears to solve [legumeinfo/microservices#33](https://github.com/legumeinfo/microservices/issues/33) as well. Feel free to push those changes to the compose files in the GCV repo. It's probably worth adding a note to the redis_loader microservice's readme too. Let me know if you'd rather I make these changes.

@alancleary if you'd like to make the changes in `main`, I could merge & verify in the gcv.legumeinfo.org branch

**Comment by alancleary** [comment]
Done in PR #415. Closing.
