### ISSUE TITLE
URL for app points to 404

### ISSUE THREAD

**Issue by cmdcolin** [legumeinfo/gcv#421]
The github repo refers to https://legumeinfo.org/gcv2 and also I believe previously referred to https://legumeinfo.org/gcv but both are not available currently, i think must be at https://gcv.legumeinfo.org! Great work on this project also :)

**Comment by adf-ncgr** [comment]
Nice- thanks for pointing that out! Indeed, we just made the switch on our legumeinfo.org site and forgot about this dangling reference. Will fix; and hopefully sometime we can talk about GCV/JBrowse2 connectivity! :)

**Comment by adf-ncgr** [comment]
fixed in c7e5bac

**Comment by cmdcolin** [comment]
yes! really trying to amp up our synteny/comparative features. definitely curious if there are any ways to integrate

**Comment by adf-ncgr** [comment]
> URL query API e.g. specifying ?loc=chr1:1-100 in URL bar (added in 1.6.4)
was a good start! looking forward to support for loc=gene_name too ;)
we are getting pretty close to releasing JBrowse2 based instances on our legumeinfo.org site and have been watching synteny/comparative feature developments with much interest. Would be fun to get together and brainstorm sometime...

**Comment by cmdcolin** [comment]
awesome that is great to hear... will definitely try to expand on that URL API it definitely is good for generating links for interoperability

**Comment by adf-ncgr** [comment]
Interoperation begins with U (RL/I) - but FAUR doesn't sound as nice...
@alancleary and @ctcncgr have also done some work using [BroadcastChannel](https://developer.mozilla.org/en-US/docs/Web/API/BroadcastChannel) to do inter-app communication, which seems pretty magical when it works (but depends on apps being hosted under the same origin)
