### ISSUE TITLE
Should the GCV and microservice compose files be combined?

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/gcv#429]
I think combining the compose files could streamline the setup process. The microservices could be under a different compose profile so only GCV runs by default. We could then aggregate all the compose related files in a single directory. When a release is tagged, this directory could be zipped as part of the automated build process and added to the release as a build artifact. This way all someone would need to do to get going with GCV is download the zip, extract it, and run the compose file it contains (maybe just include production compose files in the zip that pull containers from GHPR).

I'm specifically interested in what @nathanweeks and @adf-ncgr think of this. Thanks!

**Comment by adf-ncgr** [comment]
offhand I think it sounds reasonable, though I may not be entirely following how it would differ from the current set-up. As far as I'm concerned the main "requirements" are that we need to be able to run a client independent of running a suite of services (ie pointing a client via config to separately managed services) and we need to be able to run services independently of a client. Running them conjointly is probably most people's default use case, though, so making that as easy as possible as I think you have outlined in your proposal, sounds like a good plan.

**Comment by alancleary** [comment]
It's basically the same as the current setup except it makes the turn-key zip file easy to implement, which is what I think we really need for outside groups to hit the ground running. The stand-alone client or service scenarios will be accommodated via [compose profiles](https://docs.docker.com/compose/profiles/), i.e. these profiles could cover the various scenarios: "gcv" (runs just the GCV client), "services" (runs just the GCV microservices), "all" (runs both the GCV client and the microservices), and "redis_loader" (an existing profile that runs the Redis loader).

**Comment by alancleary** [comment]
Done in commit legumeinfo/gcv-docker-compose#363c3420ebfa7d4d2bc63b55182211780cfff03c. Closing.

**Comment by nathanweeks** [comment]
@alancleary I agree that this would seem to be a convenience for both new users and sites that deploy GCV. Will the Compose files in the legumeinfo/gcv and legumeinfo/microservices repos be deprecated & eventually removed? Otherwise, it seems updates to the Compose files in the legumeinfo/gcv-docker-compose repo would probably need to be manually kept in sync with legumeinfo/gcv or legumeinfo/microservices, and vice-versa.
