### ISSUE TITLE
add "outliers" for the query track?

### ISSUE THREAD

**Issue by adf-ncgr** [legumeinfo/gcv#8]
currently, the outliers are displayed for the result track, but not for the query track. seems like there is no reason in principle for this asymmetry. Those genes present in the query track but not in the result track could be displayed along the right hand-vertical edge of the plot area.

**Comment by alancleary** [comment]
When upgrading to D3 version 4, the dot plot viewer was reimplemented and the outliers feature was removed (commit 78b54ab8001e7289e7b630c0482f5de7296dd88c). I think there's merit for reimplementing this feature for both the query and result tracks. Switching to enhancement.

**Comment by adf-ncgr** [comment]
glad to see this live on; IIRC, Nevin asked about the asymmetry when I was demoing things to him, which made me feel like I'm starting to think like a biologist (or maybe he's starting to think like a geometer)

**Comment by alancleary** [comment]
Stale.
