### ISSUE TITLE
Cleanup branches

### ISSUE THREAD

**Issue by alancleary** [legumeinfo/gcv#848]
There's an awful lot of branches in this repo. A lot of them are from dependabot, but there's also a handful for deployments that haven't been updated in over a year. I would like to clean this up.

Can the owners of these branches either delete them or rename the branch to have the prefix `deployment/` to indicate that the branch is for a specific deployment? If there's other branches people want to keep that aren't deployment branches then can we discuss it here to best decide how to handle them? Thanks!

**Comment by alancleary** [comment]
If we want to keep a handful of non-dev branches around then we may consider creating a copy of the GCV repo to serve as a parking place for these branches, as descrived in [this Stackoverflow answer](https://stackoverflow.com/a/22767933).

**Comment by adf-ncgr** [comment]
Thanks for keeping us hygienic @alancleary. I've deleted most of the non-dependabot branches and provisionally renamed 2 using the suggested `deployment/` naming scheme. It may well be that we no longer need these two either, but I wasn't quite ready to make that call. Regarding the "parking place for branches", I will defer to you on how obnoxious you find having deployment branches in the repos if we use the naming convention you suggested. I will note that downstream on that stackoverflow you linked they note that github now does allow you to [fork within the organization](https://github.blog/changelog/2022-06-27-improved-innersource-collaboration-and-enterprise-fork-policies/).

**Comment by alancleary** [comment]
Thanks @adf-ncgr. Things are looking better already. I think it's probably not worth creating a separate repo for parking branches at this point. Thanks for the link, though. Clearly I stopped reading after the first solution!

**Comment by nathanweeks** [comment]
I think the [deployment/legumeinfo.org/gcv2](https://github.com/legumeinfo/gcv/tree/deployment/legumeinfo.org/gcv2) branch is  a historical relic that would be harmless to prune as well.

**Comment by alancleary** [comment]
Thanks Nathan. It looks like @adf-ncgr was the last person to touch that branch. Do you care if I delete it Andrew?

**Comment by adf-ncgr** [comment]
nope, I'm fine with deleting it and [deployment/legumeinfo-settings](https://github.com/legumeinfo/gcv/tree/deployment/legumeinfo-settings) as well
